// <auto-generated />
using System;
using AspMvcFrontEnd.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspMvcFrontEnd.Migrations
{
    [DbContext(typeof(VcdRentalContext))]
    [Migration("20190110035528_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspMvcFrontEnd.Models.ContactModel", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("FullName");

                    b.Property<string>("IdentityNumber");

                    b.Property<string>("PhoneNumber");

                    b.Property<int?>("TenantModelTenantId");

                    b.HasKey("ContactId");

                    b.HasIndex("TenantModelTenantId");

                    b.ToTable("ContactModel");
                });

            modelBuilder.Entity("AspMvcFrontEnd.Models.RentalPackageModel", b =>
                {
                    b.Property<int>("RentalPackageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CostPerMonth");

                    b.Property<int>("MaxVcdRental");

                    b.Property<string>("PackageName");

                    b.HasKey("RentalPackageId");

                    b.ToTable("RentalPackageModel");
                });

            modelBuilder.Entity("AspMvcFrontEnd.Models.TenantModel", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("FullName");

                    b.Property<string>("IdentityNumber");

                    b.Property<bool>("IsMemberOfAnotherRental");

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("Reference");

                    b.Property<DateTime>("RegistrationDate");

                    b.Property<int?>("SubscribePackageRentalPackageId");

                    b.HasKey("TenantId");

                    b.HasIndex("SubscribePackageRentalPackageId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("AspMvcFrontEnd.Models.ContactModel", b =>
                {
                    b.HasOne("AspMvcFrontEnd.Models.TenantModel")
                        .WithMany("ApprovedContacts")
                        .HasForeignKey("TenantModelTenantId");
                });

            modelBuilder.Entity("AspMvcFrontEnd.Models.TenantModel", b =>
                {
                    b.HasOne("AspMvcFrontEnd.Models.RentalPackageModel", "SubscribePackage")
                        .WithMany()
                        .HasForeignKey("SubscribePackageRentalPackageId");
                });
#pragma warning restore 612, 618
        }
    }
}
